### ISSUE TITLE
Failing Configuration of PR-Agent running as a GitHub Action

### ISSUE THREAD

**Issue by nmpluta** [Codium-ai/pr-agent#1068]
#### Problem Statement
I am currently not a premium user but wish to evaluate the features and capabilities provided by the PR-Agent tools. I have previously utilized the @CodiumAI-Agent bot for GitHub chat in pull requests, which worked successfully.

Presently, I am attempting to configure the tool to automatically execute the /describe, /improve, and review functionalities upon the creation or update (new changes) of a Pull Request. Following the setup instructions to Run as a GitHub Action from the documentation available at [Codium PR-Agent GitHub Action Setup](https://pr-agent-docs.codium.ai/installation/github/#run-as-a-github-action), I encountered issues that prevented successful configuration.

#### Steps Taken

1. **Addition of pr_agent.yml:**
I added the file to my repository under .`github/workflows/pr_agent.yml as indicated` in the following merge request:
[MR: https://github.com/nmpluta/telemetry-system/pull/12/files](https://github.com/nmpluta/telemetry-system/pull/12/files)

My `.github/workflows/pr_agent.yml` contains:

    ```yaml
    on:
      pull_request:
        types: [opened, reopened, ready_for_review]
      issue_comment:
    jobs:
      pr_agent_job:
        if: ${{ github.event.sender.type != 'Bot' }}
        runs-on: ubuntu-latest
        permissions:
          issues: write
          pull-requests: write
          contents: write
        name: Run pr agent on every pull request, respond to user comments
        steps:
          - name: PR Agent action step
            id: pragent
            uses: Codium-ai/pr-agent@main
            env:
              OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              github_action_config.auto_review: "true" # enable auto review
              github_action_config.auto_describe: "true" # enable auto describe
              github_action_config.auto_improve: "true" # enable auto improve
    ```

   Note: I added the settings for enabling review, describe, and improve functionalities according to the instructions in the [automation guide](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-action). The documentation suggests that both uppercase and lowercase letters are acceptable for these settings. For instance, github_action_config.auto_review should work the same as GITHUB_ACTION_CONFIG.AUTO_REVIEW. However, the presence of two different approaches in the documentation raises concerns about potential inconsistencies.

2. **Adding the OpenAI Key Secret**
   Following the second step in the setup guide, I added the OpenAI key secret to the repository under `Settings > Secrets and variables > Actions > New repository secret > Add secret` with:
   - Name: `OPENAI_KEY`
   - Secret: `<your key>`

   The documentation did not specify how to generate this key.  I was trying to figure it out and I found out some information here: https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/.secrets_template.toml#L10.
That's why I generated the `read-and-write API resources` key using the site: https://platform.openai.com/api-keys with the same name as in Github settings. Is this correct? 

![open-ai-key_platform_site](https://github.com/user-attachments/assets/7f23f166-28ce-4b6a-be18-8a7404e7991f)
[
![open-ai_key](https://github.com/user-attachments/assets/39f1b7a1-0d47-4988-8317-ce497d8ddf83)
](url)

According to the documentation:
`The GITHUB_TOKEN secret is automatically created by GitHub.`  so I didn't create it by my own.

3. **Merging Configuration**
   I merged the following pull request that added the `.github/workflows/pr_agent.yml` file to the main branch: [Pull Request](https://github.com/nmpluta/telemetry-system/pull/12/files).

At the end, after the merge,  I opened the MR to validate if it works and no `/review`, `/describe` or `/improve` functionality was triggered by the `github-actions` bot -> https://github.com/nmpluta/telemetry-system/pull/15

#### Issues/Findings

1. **Failure to Trigger Expected Functionalities**
   After merging the changes and opening a new pull request to validate the configuration, the expected functionalities (/review, /describe, /improve) were not triggered by the GitHub Actions bot.

2. **Lack of Documentation on Key Generation**
   The documentation does not explain how the OpenAI key should be generated, leading to uncertainty about whether the correct key was used. I found additional information on generating the key from a different source, which may not be aligned with the pr-agent's requirements.

3. **Inconsistent Documentation**
   The documentation contains inconsistent approaches regarding the configuration keys (uppercase vs. lowercase), which could lead to potential misconfigurations.

#### Request for Support
I seek guidance and support to resolve these issues and enable the automated review, description, and improvement functionalities for pull requests as intended. Specifically, I need assistance in:

1. Verifying the correctness of my `.github/workflows/pr_agent.yml` configuration.
2. Confirming the proper generation and usage of the OpenAI key.
3. Ensuring that the configuration keys are correctly recognized by the pr-agent.

Could you please assist in identifying any misconfigurations or provide further instructions to ensure the setup works correctly?
