### ISSUE TITLE
When the bot doesn't have any PR suggestions, there's no checkbox to add the 2nd review

### ISSUE THREAD

**Issue by ChrisWiles** [Codium-ai/pr-agent#1080]
When the bot doesn't have any PR suggestions, there's no checkbox to add the 2nd review

`pr_code_suggestions.demand_code_suggestions_self_review: true`

![image](https://github.com/user-attachments/assets/4000956e-d329-4915-be5f-39e4797d06b0)

**Comment by mrT23** [comment]
this is not a proper way to open an issue

give dramatically more details, including reproduction code

**Comment by ChrisWiles** [comment]
```
# Codium-ai/pr-agent GitHub action automates PR reviews by analyzing pull requests and providing feedback such as:
# - Auto Description: Crafts PR descriptions with title, type, summary, and labels.
# - Auto Review: Offers feedback on PR theme, type, tests, security, and improvement suggestions.
# - Question Answering: Responds to queries about the PR.
# It can be set to run on every PR or triggered manually and integrates with other GitHub actions.
# https://github.com/Codium-ai/pr-agent

name: PR GPT Agent

on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run the GPT agent on every pull request and respond to user comments
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Use a PAT so that other workflows can be triggered by bot comments https://github.com/orgs/community/discussions/27028
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
          # https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml
          config.max_model_tokens: 128000 # 128K context window for the GPT-4 Omni model
          config.model: 'gpt-4o'
          config.max_description_tokens: 1000 # max token length of the PR description
          config.max_commits_tokens: 500 # max token length for reading PR commits
          config.verbosity_level: 2 # 0 = silent, 1 = errors, 2 = warnings
          github_action.auto_describe: 'true' # Automatically describe the PR
          # github_action.auto_improve: 'true' # Automatically suggest code improvements
          github_action.auto_review: 'true' # Automatically review the PR
          pr_description.add_original_user_description: 'true' # Add the original user description to the PR description
          # pr_description.keep_original_user_title: 'true'
          # pr_description.publish_description_as_comment: 'true'
          pr_description.extra_instructions: ''
          pr_reviewer.enable_review_labels_effort: 'true'
          pr_reviewer.num_code_suggestions: 8 # Number of code suggestions to provide, default is 4
          pr_reviewer.minimal_minutes_for_incremental_review: 30 # only rereview PR that have had 30 mins since the last review
          pr_code_suggestions.demand_code_suggestions_self_review: true
 ```
