### ISSUE TITLE
config.ignore.glob doesn't seem to work

### ISSUE THREAD

**Issue by dbarrosop** [Codium-ai/pr-agent#1213]
Hello,
I am struggling a bit with this one and I am sure it is something silly. I have a workflow with the following action:

```
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@v0.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          config.max_model_tokens: 100000
          config.model: "anthropic/claude-3-5-sonnet-20240620"
          config.model_turbo: "anthropic/claude-3-5-sonnet-20240620"
          config.ignore.glob: "['vendor/**','**/client_gen.go','**/models_gen.go','**/generated.go','**/*.gen.go']"
```

However, `config.ignore.glob` seems to take no effect. In the logs I can see:

```
{"text": "Relevant configs\n", "record": {"elapsed": {"repr": "0:00:04.568666", "seconds": 4.568666}, "exception": null, "extra": {"artifacts": {"pr_description": {"publish_labels": true, "add_original_user_description": true, "generate_ai_title": false, "use_bullet_points": true, "extra_instructions": "", "enable_pr_type": true, "final_update_message": false, "enable_help_text": false, "enable_help_comment": true, "publish_description_as_comment": false, "publish_description_as_comment_persistent": true, "enable_semantic_files_types": true, "collapsible_file_list": "adaptive", "inline_file_summary": false, "use_description_markers": false, "include_generated_by_header": true, "enable_large_pr_handling": true, "max_ai_calls": 4, "async_ai_calls": true, "mention_extra_files": true}, "config": {"max_model_tokens": 100000, "model": "anthropic/claude-3-5-sonnet-20240620", "model_turbo": "anthropic/claude-3-5-sonnet-20240620", "ignore": {"glob": ["vendor/**", "**/client_gen.go", "**/models_gen.go", "**/generated.go", "**/*.gen.go"]}, "enable_custom_labels": false, "fallback_models": ["gpt-4o-2024-05-13"], "git_provider": "github", "publish_output": true, "publish_output_progress": true, "verbosity_level": 0, "use_extra_bad_extensions": false, "use_wiki_settings_file": true, "use_repo_settings_file": true, "use_global_settings_file": true, "ai_timeout": 120, "skip_keys": [], "max_description_tokens": 500, "max_commits_tokens": 500, "custom_model_max_tokens": -1, "patch_extension_skip_types": [".md", ".txt"], "allow_dynamic_context": false, "max_extra_lines_before_dynamic_context": 10, "patch_extra_lines_before": 3, "patch_extra_lines_after": 1, "secret_provider": "", "cli_mode": false, "ai_disclaimer_title": "", "ai_disclaimer": "", "output_relevant_configurations": false, "large_patch_policy": "clip", "seed": -1, "temperature": 0.2, "ignore_pr_title": ["^\\[Auto\\]", "^Auto"], "ignore_pr_target_branches": [], "ignore_pr_source_branches": [], "ignore_pr_labels": [], "is_auto_command": false, "enable_ai_metadata": false}}}, "file": {"name": "pr_description.py", "path": "/app/pr_agent/tools/pr_description.py"}, "function": "run", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 86, "message": "Relevant configs", "module": "pr_description", "name": "pr_agent.tools.pr_description", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140307224894336, "name": "MainThread"}, "time": {"repr": "2024-09-09 20:15:41.677659+00:00", "timestamp": 1725912941.677659}}}
```

Which seems to indicate the config is being picked. However, files like:

```
path/to/client_gen.go
path/to/models_gen.go
```

are still being processed as I am getting suggestions for those.

P.S: awesome work with this extensions
