### ISSUE TITLE
Github Actions: VertexAI is not working 

### ISSUE THREAD

**Issue by atan4-quantium** [Codium-ai/pr-agent#1229]
Hi all!

I was following the instructions to self host using github action: https://pr-agent-docs.codium.ai/installation/github/

I was able to get the github action working, but it seems like it is running OpenAI Inference? I have pasted my `pr_agent.yml` below, any suggestions would be highly appreciated.

`pr_agent.yml` 
```
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          VERTEXAI.VERTEX_PROJECT: ${{ secrets.VERTEX_PROJECT }}
          VERTEXAI.VERTEX_LOCATION: ${{ secrets.VERTEX_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: vertex_ai/gemini-1.5-flash
          config.model_turbo: vertex_ai/gemini-1.5-flash
          config.fallback_models: vertex_ai/codechat-bison
          litellm.set_verbose: True
```
---

Logs

![image](https://github.com/user-attachments/assets/97efb786-8f7a-4c90-9d23-4a03b74e3c43)
![image](https://github.com/user-attachments/assets/6d2c95b3-b5e2-4bac-95b2-f97187d1b1ef)
