### ISSUE TITLE
Failed to update pull request, error

### ISSUE THREAD

**Issue by dreamlychina** [Codium-ai/pr-agent#1284]
AI response:

```yaml
type:
- Enhancement
description: |-
  - Added the missing `debug_contour` command for the 'r2.csv' file in the training script.
  - Updated the training script to include the necessary path for the `test_v5` utility.
title: |-
  Update training script with missing debug command and utility path
```
2024-10-11 13:11:08.235 | ERROR    | pr_agent.git_providers.bitbucket_server_provider:publish_description:448 - Failed to update pull request, error: This pull request has already been merged.
2024-10-11 13:11:08.235 | ERROR    | pr_agent.tools.pr_description:run:164 - Error generating PR description 5: This pull request has already been merged.
