### ISSUE TITLE
Does Changelog works with github action?

### ISSUE THREAD

**Issue by anujkumar-df** [Codium-ai/pr-agent#1377]
```
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_UPDATE_CHANGELOG.PUSH_CHANGELOG_CHANGES: true
```

Still on opening a new PR, no change log is generated. Am I missing something?
