### ISSUE TITLE
How to start the webhook server for gitlab?

### ISSUE THREAD

**Issue by Hyp3rSoniX** [Codium-ai/pr-agent#1456]
Hi, I'm trying to start a webhook server via a docker-compose file, but I get the following error:
```
usage:     Usage: cli.py --pr-url=<URL on supported git hosting service> <command> [<args>].

    For example:
    - cli.py --pr_url=... review
    - cli.py --pr_url=... describe
    - cli.py --pr_url=... improve
    - cli.py --pr_url=... ask "write me a poem about this PR"
    - cli.py --pr_url=... reflect
    - cli.py --issue_url=... similar_issue
    Supported commands:
    - review / review_pr - Add a review that includes a summary of the PR and specific suggestions for improvement.
    - ask / ask_question [question] - Ask a question about the PR.
    - describe / describe_pr - Modify the PR title and description based on the PR's contents.
    - improve / improve_code - Suggest improvements to the code in the PR as pull request comments ready to commit.
    Extended mode ('improve --extended') employs several calls, and provides a more thorough feedback
    - reflect - Ask the PR author questions about the PR.
    - update_changelog - Update the changelog based on the PR's contents.
    - add_docs
    - generate_labels
    Configuration:
    To edit any configuration parameter from 'configuration.toml', just add -config_path=<value>.
    For example: 'python cli.py --pr_url=... review --pr_reviewer.extra_instructions="focus on the file: ..."'
  

AI based pull request analyzer
positional arguments:
 {auto_review,answer,review,review_pr,describe,describe_pr,improve,improve_code,ask,ask_question,ask_line,update_changelog,config,settings,help,similar_issue,add_docs,generate_labels}

                        The
  rest
options:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --pr_url PR_URL       The URL of the PR to review
  --issue_url ISSUE_URL
                        The URL of the Issue to review
```

my docker-compose file:
```
services:
  pr-agent:
    image: codiumai/pr-agent:latest
    restart: unless-stopped
    network_mode: host
    environment:
    - CONFIG.GIT_PROVIDER=gitlab
    - GITLAB.URL=https://gitlab.myhost
    - GITLAB.PERSONAL_ACCESS_TOKEN=glpat-redacted
    - GITLAB.SHARED_SECRET=YYredacted
    - OPENAI.KEY=sk-redacted
    - CONFIG.MODEL=gpt-4o
    - CONFIG.DEPLOYMENT_TYPE=gitlab
    - GITLAB.HANDLE_PUSH_TRIGGER=true
```

I also tried to adapt the config files directly, build the docker image that way and start it, but I got the same error.

In the provided examples of the dokumentation the docker run commands have arguments added to check for an already existing PR. 
But how can I start a webhook server for gitlab?

I think I'm missing something.

I did try to follow this guide: https://qodo-merge-docs.qodo.ai/installation/gitlab/#run-a-gitlab-webhook-server
