### ISSUE TITLE
Lack of release versioning

### ISSUE THREAD

**Issue by szecsip** [Codium-ai/pr-agent#190]
Currently, the development process incorporates version control; however, we are facing a critical challenge due to the absence of structured release versioning. While the codebase is versioned internally, we lack the practice of creating distinct releases. This is leading to potential instability in the development environment, as the absence of well-defined release points can introduce bugs and errors with each subsequent development iteration.

**Impact:**
The absence of clear release versioning means that we are only able to access the latest version of the codebase. Without established release points, we lack a stable reference to which we can easily revert in the event of critical issues. This holds true irrespective of whether we are utilizing GitHub Actions, Docker images, or other development tools. Consequently, our ability to ensure a stable and reliable development environment is compromised.

**Comment by idavidov** [comment]
i mean while i would suggest use one of these 2 methods(maybe it good to add to INSTALL section also, let me now if it make sense
for docker images 
```
docker run --rm -it -e OPENAI.KEY=<your key> -e GITHUB.USER_TOKEN=<your token> codiumai/pr-agent@sha256:71b5ee15df59c745d352d84752d01561ba64b6d51327f97d46152f0c58a5f678 --pr_url <pr_url> review
docker run --rm -it -e OPENAI.KEY=<your key> -e GITHUB.USER_TOKEN=<your token> codiumai/pr-agent@sha256:71b5ee15df59c745d352d84752d01561ba64b6d51327f97d46152f0c58a5f678 --pr_url <pr_url> ask "<your question>"

```

for github actions:
```yaml
on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: **Codium-ai/pr-agent@<commit_sha>**
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
