### ISSUE TITLE
Unable to use Github Action anymore

### ISSUE THREAD

**Issue by DMC09** [Codium-ai/pr-agent#274]
Last week the PR agent was working fine however this week I noticed it fails to run. When reading the logging it seems like it doesn't have access to the gpt-4 model. But I am also getting a rate limit error. Not sure what I need to do. I checked the Open AI console and it seems like I haven't used any of my 18$ worth of credit. I just used the .yml file in the docs. 

I have attached the full logging error in a .txt file

[PRagent_error.txt](https://github.com/Codium-ai/pr-agent/files/12516004/PRagent_error.txt)

**Comment by mrT23** [comment]
are you able to access gpt-4 otherwise ?

for example via the playground:
https://platform.openai.com/playground?model=gpt-4

**Comment by DMC09** [comment]
Hello @mrT23 , Thanks for the response, 

Unfortunately no, I get the same error 

The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.


I never set up which model to use because I just used the .yml file in the docs. Is there a way I can specific which model to use??

**Comment by okotek** [comment]
You can override the model by specifying it as an environment variable. If you're using GitHub Actions, you might want to add under the env: section - 

CONFIG.MODEL: gpt-3.5-turbo

**Comment by mrT23** [comment]
Similar Issues:

1. [Running Github Action: openai.error.RateLimitError](https://api.github.com/repos/Codium-ai/pr-agent/issues/104)

2. [Github actions error](https://api.github.com/repos/Codium-ai/pr-agent/issues/111)

3. [Issue on github action](https://api.github.com/repos/Codium-ai/pr-agent/issues/218)

**Comment by mrT23** [comment]
Similar Issues:

1. [Running Github Action: openai.error.RateLimitError](https://github.com/Codium-ai/pr-agent/issues/104)

2. [Github actions error](https://github.com/Codium-ai/pr-agent/issues/111)

3. [Issue on github action](https://github.com/Codium-ai/pr-agent/issues/218)

**Comment by DMC09** [comment]
Okay So I ended up Using this environment variable and the action runs successfully now. However it only acknowledges my comments. I haven't seen it respond yet. 

here is my [PR.](https://github.com/DMC09/grocer-app-ui/pull/14) 

as you can see I tagged the CodiumAI-Agent and asked it to describe. It reacted with the eyes emoji but did not response. Do I need to add the permission in the .yml file? 

```yaml
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.MODEL: gpt-3.5-turbo


```
