### ISSUE TITLE
Adding Descriptive Comments or Reviews Directly Upon PR Creation

### ISSUE THREAD

**Issue by hmedat** [Codium-ai/pr-agent#326]
### Description

We are using GitHub Actions to integrate with `pr-agent`. The current configuration is as follows:

```yaml
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The workflow is successfully triggered when a new pull request is created. However, we have two issues:

1. We want to automatically add descriptive comments or reviews to the PR right after it's created.
2. Adding "/review" or any other command in the PR comments does not seem to trigger anything.
