### ISSUE TITLE
Re-run properly on every PR commit?

### ISSUE THREAD

**Issue by georgeseifada** [Codium-ai/pr-agent#328]
The GitHub Action is rerunning on every commit. But the original comment does not change, nor are any new code suggestions made when there are new commits even if they have significant changes. Can we make it so that it will update the comment / properly re-run the review when there are new commits in the PR?

**Comment by georgeseifada** [comment]
My workflow file:

```
name: "🕵️ PR Agent"
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent # On PRs and comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_INTERNAL_API_KEY_CODIUMAI_PR_AGENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 5
          PR_REVIEWER.INLINE_CODE_COMMENTS: true
          PR_REVIEWER.ASK_AND_REFLECT: true
```
