### ISSUE TITLE
Inline comments aren't working

### ISSUE THREAD

**Issue by slice-sarthakd** [Codium-ai/pr-agent#375]
<img width="919" alt="Screenshot 2023-10-16 at 12 09 27 PM" src="https://github.com/Codium-ai/pr-agent/assets/106574498/05a7a5ac-cf9f-48c4-ac18-fe25a8dd580f">

In the release notes it's mentioned that inline PR comments supports are added. But when I integrated with my project with azure openai as my LLM, the comments are coming in the summary instead of on the action code block. Please let me know if I am missing something. 

My github action file looks like this

```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_TYPE: 'azure'
          OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          OPENAI_API_BASE: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          OPENAI.DEPLOYMENT_ID: ${{ secrets.AZURE_OPENAI_DID }}
          OPENAI.CONFIG_MODEL: 'gpt-4'
```
