### ISSUE TITLE
Issue with Azure DevOps Integration in Docker Deployment

### ISSUE THREAD

**Issue by moccajoghurt** [Codium-ai/pr-agent#378]
I encountered an error while running pr-agent through Docker with a configuration aimed at Azure DevOps integration. Despite setting Azure DevOps environment variables, the script defaults to requiring a GitHub token. The error tracebacks are from github_provider.py indicating a missing GitHub user_token. I intend to use pr-agent for Azure DevOps, not GitHub, and don’t understand why a GitHub token is required. Please advise on resolving this issue for a successful Azure DevOps integration. Below is my docker-compose configuration and the error message received.

```
version: '3.1'
services:
  pr-agent:
    image: codiumai/pr-agent:latest
    environment:
      - OPENAI_KEY=my_key
      - AZURE_DEVOPS_PAT=my_pat
      - AZURE_DEVOPS_ORG=my_url
    command: --pr_url my_pr_url.com review
```
Error:
> ... (Error traceback)
ValueError: GitHub token is required when using user deployment. See: https://github.com/Codium-ai/pr-agent#method-2-run-from-source

Thank you for your assistance.

**Comment by mrT23** [comment]
@moccajoghurt  take a look at:
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#azure-devops-provider

have you done for example:

config.git_provider="azure" 
?

**Comment by moccajoghurt** [comment]
Thank you, now it works. I had to adjust the docker-compose.yml file like this:
```
version: '3.1'
services:
  pr-agent:
    image: codiumai/pr-agent:latest
    environment:
      - OPENAI_KEY=my_key
    volumes:
      - ./configuration.toml:/app/pr_agent/settings/configuration.toml
      - ./secrets.toml:/app/pr_agent/settings/.secrets.toml
    command: --pr_url my_pr_url.com review

```
