### ISSUE TITLE
Re-running review when PR is synchronized

### ISSUE THREAD

**Issue by nataliezeller1** [Codium-ai/pr-agent#504]
I'm running the pr-agent as a git action. When a PR is opened, the review is running and a comment is added. 
Is there a way to re-run review automatically also when the PR gets synchronized with additional commits?

**Comment by ken109** [comment]
If you set up the workflow as below, the workflow will start twice, but PR-Agent can be started for each syncronize event.

```
name: "PR Agent"

on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Review command
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "/review"

      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
```
