### ISSUE TITLE
Nothing happens? What am I missing?

### ISSUE THREAD

**Issue by dep** [Codium-ai/pr-agent#510]
My action, which completes successfully:

```
name: AI Generator ✨

on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action.auto_review: "true"
          github_action.auto_describe: "true"
          github_action.auto_improve: "true"
          pr_description.enable_file_walkthrough: "true"
          pr_description.use_description_markers: "true"
```

My PR template:

```
## https://foo.atlassian.net/browse/<ADD JIRA ID>

### Description
pr_agent:summary

### Overview of Changes
pr_agent:walkthrough

### Gotchas
-

### Requires
-

### Checklist
- [ ] Web-impacting / breaking changes were verified
```

The action runs but nothing happens.  I also tried leaving a comment `/describe` and again nothing happens. What am I missing here?
