### ISSUE TITLE
Getting error on Bitbucket pipeline 

### ISSUE THREAD

**Issue by RavianXReaver** [Codium-ai/pr-agent#526]
So my pipeline is exacaly as mentioned in the documents.

```yaml
pipelines:
  pull-requests:
    '**':
      - step:
          name: PR Agent Review
          image: python:3.10
          services:
            - docker
          script:
            - docker run -e CONFIG.GIT_PROVIDER=bitbucket -e OPENAI.KEY=$OPENAI_API_KEY -e BITBUCKET.BEARER_TOKEN=$BITBUCKET_BEARER_TOKEN codiumai/pr-agent:latest --pr_url=https://bitbucket.org/$BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG/pull-requests/$BITBUCKET_PR_ID review
```
            
However, I do get this error: 
`docker: invalid reference format: repository name must be lowercase.`

What I would like to know is that, what would be the correct position of these arguments for the script?
