### ISSUE TITLE
Issue with GitHub Action and GPT Model Selection

### ISSUE THREAD

**Issue by imcodingideas** [Codium-ai/pr-agent#538]
## Summary

I am currently using a GitHub Action in my workflow, but I'm encountering an unexpected response. Despite having a balance in my account, the action defaults to using `gpt-3.5-turbo-16k` instead of `gpt-4.0`.

### Screenshot of the Issue 

(Full error log is available in the attached screenshot.)

![Screenshot 2023-12-19 at 7 50 27 PM](https://github.com/Codium-ai/pr-agent/assets/5374985/b183200a-8cac-4f6b-aba9-dbc9f424d694)

![Screenshot 2023-12-19 at 7 57 59 PM](https://github.com/Codium-ai/pr-agent/assets/5374985/c37427fc-0fdd-419e-9d40-997423860991)

### GitHub Action Configuration

Here is the relevant part of my GitHub Action configuration:

```
name: PR Agent

on:
  pull_request:
  issue_comment:

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run on every pull request, and respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION.AUTO_REVIEW: true
          GITHUB_ACTION.AUTO_IMPROVE: true
```

## Question

Is there a specific configuration or step required to ensure the GitHub Action utilizes gpt-4.0 instead of defaulting to gpt-3.5-turbo-16k? Do I need to use gpt-4.0 specifically? 

Any guidance or suggestions would be greatly appreciated.
