### ISSUE TITLE
/describe doesn't update description when creating a PR [Github app]

### ISSUE THREAD

**Issue by erlichmen** [Codium-ai/pr-agent#595]
I have install the agent (v0.11 at the moment) and it updates the PR but not the description with the markers.
calling /describe manually will update the template

I have the following config:
<details>
<summary>pr_agent config</summary>

```toml
[github_app]
handle_pr_actions = ['opened', 'reopened', 'ready_for_review', 'review_requested']
pr_commands = [
  "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true --pr_description.use_description_markers=true",
  "/review",
]
handle_push_trigger = true
push_commands = [
  "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true --pr_description.use_description_markers=true",
  "/review -i --pr_reviewer.remove_previous_review_comment=true",
]

[config]
verbosity_level=2
```
</details>

and the following template:

<details>
<summary>PR templete</summary>

```markdown
## PR Type
pr_agent:type

## PR Description
pr_agent:summary

## PR Walkthrough
pr_agent:walkthrough

## PR Summary
<!-- Summary of main changes here -->
```
</details>

**Comment by mrT23** [comment]
Hi @erlichmen 
thanks for the well-written issue

I followed your recipe, and did get markers, see pictures below.

Some thoughts\guesses:

1) try working against the latest version of PR-Agent, and not 0.11. maybe we solved this issue since ?

2) try this configuration instead:
```
[github_app]
handle_pr_actions = ['opened', 'reopened', 'ready_for_review', 'review_requested']
pr_commands = [
  "/describe",
  "/review",
]

[pr_description]
use_description_markers=true

[config]
verbosity_level=2
```

(3) take a look at your log and try to see what happened. since you are not using our manged hosting, I am limited in the amount of QA I can provide there


![image](https://github.com/Codium-ai/pr-agent/assets/21198860/7ffbf5b5-ad0b-42b2-bbb5-a4f9f6cf6454)
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/a55c1b26-79d5-40c1-90fd-da595a265cba)
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/322d6941-3937-43aa-9681-0a5c9aabb794)

**Comment by erlichmen** [comment]
@mrT23 I tried the config you suggested and it update the markers on new PR.
v0.11 is the latest at the moment. 
I the debug logs the only line that is relevant Is:
```
2024-01-15 07:44:54.566 | INFO     | pr_agent.git_providers.utils:apply_repo_settings:29 - Applying repo settings for section GITHUB_APP, contents: {'handle_pr_actions': ['opened', 'reopened', 'ready_for_review', 'review_requested'], 'pr_commands': ['/describe', '/review'], 'handle_push_trigger': True, 'push_commands': ['/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true --pr_description.use_description_markers=true', '/review -i --pr_reviewer.remove_previous_review_comment=true']}
2024-01-15 07:44:54.575 | INFO     | pr_agent.git_providers.utils:apply_repo_settings:2[9](https://github.com/doitintl/cmp-main/actions/runs/7525769177/job/20482665801?pr=19889#step:3:10) - Applying repo settings for section PR_DESCRIPTION, contents: {'use_description_markers': True}
```

but I can't see anything else relevant to it

**Comment by mrT23** [comment]
v0.11 is not the "latest". its a stable version

`docker pull codiumai/pr-agent:github_app` is the latest, updated 4 days ago
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/2b704ec3-3033-4af8-9e3f-fe08bc33b1e3)

**Comment by erlichmen** [comment]
I'm using Codium-ai/pr-agent@main for the github app, I just assume that v0.11 is that latest.
is there anything that I can use instead of @main?

**Comment by mrT23** [comment]
i dunno. i tried to replicate here:
https://github.com/mrT23/pr-agent
https://github.com/mrT23/pr-agent/pull/18
it worked

you are welcome to try there yourself

**Comment by erlichmen** [comment]
Thank you for the effort  in resolving it, I looked at your example repo and I coin't find the PR template for the repo in .github/PULL_REQUEST_TEMPLATE.md.
We are using PR template maybe that is the difference?

**Comment by erlichmen** [comment]
I created a [poc repo](https://github.com/doitintl/pr-agent-markers-poc/pull/1) for this and open a new PR same issue, description is not getting updated.

(Also if the OpenAI key is not set only a log message is displayed  while I think that the action should fails, but thats a diffrent topic)

**Comment by mrT23** [comment]
@erlichmen 
i am a bit confused.
you said you are using **githubApp**
yet this folder:
https://github.com/doitintl/pr-agent-markers-poc/blob/main/.github/workflows/pr-agent.yml
defines **githubAction**

If you are indeed use **github action**, the way to use markers is like this:
```

[pr_description]
use_description_markers=true
```

**Comment by erlichmen** [comment]
yes, my bad I mixed up github app and github action (maybe if possible config file should be the same for both flavors). 
Anyways, I added this to the action file and it works now:
```yaml
    steps:
      - name: PR Agent action step
        id: pr-agent
        uses: Codium-ai/pr-agent@main
        env: 
          OPENAI_KEY: ${{ secrets.OPENAI_KEY_FOR_PR_AGENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This was missing 
          github_action.auto_review: "true"
          github_action.auto_describe: "true"
          github_action.auto_improve: "false"
          github_action.pr_description.use_description_markers: "true"
```
