### ISSUE TITLE
Select desired AI model in pr_agent.yml?

### ISSUE THREAD

**Issue by perryraskin** [Codium-ai/pr-agent#647]
Is there a way to select the AI model that we want to use?

For example:

```
pr_agent_job:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    model: gpt-3.5-turbo-1106
```
