### ISSUE TITLE
Can I change the response language to something other than English?

### ISSUE THREAD

**Issue by CatsMiaow** [Codium-ai/pr-agent#822]
I want to output the language of a country other than English (e.g. Japanese, Korean, etc.) in the bot's pull request comment responses.
> https://github.com/Codium-ai/pr-agent/pull/732#issuecomment-1975099159

I can't seem to find it in the environment configuration, is there any way to change the output language?
> https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml

**Comment by mrT23** [comment]
use the 'extra_instructions' field of each tool

https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L38

**Comment by mrT23** [comment]
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/278eb069-cee8-4d91-9acd-005cbec25016)
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/b802d75b-4d6b-48c1-ab99-ea12dbd8ea40)

**Comment by jason-hwang** [comment]
How about something like this?

in `pr_agent.toml`
```
[pr_custom_prompt]
prompt = """\
The description of 'code suggestions', 'pr description', and 'code review' should be in the Japanese language.
"""
```

**Comment by mrT23** [comment]
you are using the wrong configuration. Use "extra_instructions" for the relevant tool

anyway, the field names are defined in the prompt (in English). So you cant change them (the left column)
But the **answers** (right column) can be given in Japanese. give a clear coherent prompt.

**Comment by jason-hwang** [comment]
> you are using the wrong configuration. Use "extra_instructions" for the relevant tool
> 
> anyway, the field names are defined in the prompt (in English). So you cant change them (the left column) But the **answers** (right column) can be given in Japanese. give a clear coherent prompt.


@mrT23 
Thank you for your response. I resolved the issue using `extra_instructions`. I appreciate you for creating such a wonderful product.

**Comment by mrT23** [comment]
p.s

https://github.com/Codium-ai/pr-agent/pull/1355#issuecomment-2483338247

**Comment by haesungJoo** [comment]
@mrT23 
Does `extra_instructions` configuration only allows at **Pro** license like you said at this #1355 issue?

I tried to change language but it only applies to `/describe` command. 

I'm currently using github action code below.
```
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.MODEL: "gpt-4o-mini"
          CONFIG.MODEL_TURBO: "gpt-4o-2024-08-06"
          CONFIG.FALLBACK_MODELS: "gpt-4o-mini-2024-07-18"
          pr_reviewer.extra_instructions: "Answer in korean" # /review 
          pr_description.extra_instructions: "Answer in korean" # /describe
          pr_questions.extra_instructions: "Answer in korean" # /ask
          pr_code_suggestions.extra_instructions: "Answer in korean" # /improve
```

Does configuration setting wrong? 😢
