### ISSUE TITLE
how to configure anthropic on github ?

### ISSUE THREAD

**Issue by abeatbeyondlab** [Codium-ai/pr-agent#823]
this is the config for openai
```
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

I am not understanding what I have to do based on the guide that i found here 
https://github.com/Codium-ai/pr-agent/blob/main/docs/docs/usage-guide/additional_configurations.md

can you help me ?

what github secrets do I have to add ? 

thank you
