### ISSUE TITLE
[GitHub Actions] How do I configure using `.pr_agent.toml` file?

### ISSUE THREAD

**Issue by psbss** [Codium-ai/pr-agent#856]
Hello

I'm using GitHub actions PR-Agent. I would like to configure using `.pr_agent.toml` file but It did not work.
I think I created it correctly, so PR-Agent(GitHub Actions) doesn't support `.pt_agent.toml` config file or do We need to use PR-Agent Pro?

file name: this is root directory of my repo.
![image](https://github.com/Codium-ai/pr-agent/assets/24839924/a9b5d95e-91da-4d17-945d-51e936558454)

<details><summary><code>.pr_agent.toml</code></summary>

```toml
# PR-Agent の設定ファイル

[pr_reviewer]
extra_instructions = ""
enable_review_labels_security = false
enable_review_labels_effort = false
require_can_be_split_review = true
enable_auto_approval = true
maximal_review_effort = 1
```

</details> 

<details><summary><code>.github/workflows/pr-agent-on-comment.yml</code></summary>

```yml
name: pr-agent-commented

on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    name: PR Agent
    runs-on: ubuntu-latest
    if: github.event.sender.type != 'Bot' &&
        github.event.issue.state == 'open' &&
        github.event.issue.pull_request != null &&
        startsWith(github.event.comment.body, '/')
    steps:
      - name: PR Agent actions step
        id: pr-agent
        uses: Codium-ai/pr-agent@eff6468651c8acce5ee15ff686e8b772fe386212
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>
