### ISSUE TITLE
Issue: Failed to validate secret

### ISSUE THREAD

**Issue by kanavchopra30** [Codium-ai/pr-agent#970]
I am trying to run pr-agent using gitlab webhooks using docker. 

I have made the following changes in the mentioned files
In configuration.toml file
1. git_provider: gitlab
2. [gitalb]
    url: https://www.example.com

In .secrets.toml file
1. [openai]
    key = ""
2. [gitlab]
    personal_access_token = ""
    shared_secret = ""
    
 My docker-compose.yml file:
 ````
version: '3.2'

services:
  pr-agent:
    image: codiumai/pr-agent:gitlab_webhook
    restart: always
    volumes:
     - ../pr_agent/settings/configuration.toml:/app/pr_agent/pr_agent/settings/configuration.toml
     - ../pr_agent/settings/.secrets.toml:/app/pr_agent/pr_agent/settings/.secrets.toml
    ports:
     - 9101:3000
````
     
 And also I have added the webhooks, and sercrets and triggers as comment and merge requst but when I comment the pr-agent command it shows the following error:
 ` {"text": "Failed to validate secret\n", "record": {"elapsed": {"repr": "1:19:06.469773", "seconds": 4746.469773}, "exception": null, "extra": {}, "file": {"name": "gitlab_webhook.py", "path": "/app/pr_agent/servers/gitlab_webhook.py"}, "function": "inner", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 104, "message": "Failed to validate secret", "module": "gitlab_webhook", "name": "__main__", "process": {"id": 1, "name": "MainProcess"}, "thread": {"id": 140351802588032, "name": "MainThread"}, "time": {"repr": "2024-06-14 08:21:46.940004+00:00", "timestamp": 1718353306.940004}}}`

**Comment by mrT23** [comment]
we cannot debug your personal deployment.

you are welcome to try pr-agent-pro, where installation is easier

**Comment by SezBulent** [comment]
I am sorry, but this is the stupidest comment I've recently seen on an issue, especially leading to instantly closing it.

I've recently encountered the same issue and of course, if we do something certainly wrong, at least let's see what is wrong, especially when the documentation is clearly lacking information and it seems like it was written in a hurry, instead of proposing to try pr-agent-pro.

@kanavchopra30 have you managed to find where the problem is from?

**Comment by mrT23** [comment]
blocked a user due to inappropriate language

**Comment by luozhijunroy18** [comment]
![Image](https://github.com/user-attachments/assets/b62c8ba3-0de9-40e7-a238-389d2e65d326)

Maybe you changed the url and the Secret was cleaned up automatically, so you need to try typing it again

**Comment by jyotendra** [comment]
I assume that you are using the gitlab setup guide: https://docs.pr-agent.ai/installation/gitlab/
and more specifically the guide for setup via webhook: https://docs.pr-agent.ai/installation/gitlab/#run-a-gitlab-webhook-server

If so, I want to attract your attention to these two variables:
1. GITLAB__PERSONAL_ACCESS_TOKEN - this is your reviewer bot PAT
2. GITLAB__SHARED_SECRET - this is what you will need to put in the webhook secret (in the [image](https://github.com/The-PR-Agent/pr-agent/issues/970#issuecomment-2680157423) attached by [luozhijunroy18](https://github.com/luozhijunroy18))

Once you create the webhook you can test it by emitting a 'Merge Request Event'. Attch to your docker container to see the logs flowing: `docker logs -f <container-id>`.

It helps to boot things via compose. I use this (proxy via traefik):

```
services:
  reviewer:
    image: ${REGISTRY_IMAGE}
    restart: unless-stopped
    environment:
      CONFIG__GIT_PROVIDER: ${CONFIG__GIT_PROVIDER:-gitlab}
      GITLAB__URL: ${GITLAB__URL}
      GITLAB__PERSONAL_ACCESS_TOKEN: ${GITLAB__PERSONAL_ACCESS_TOKEN}
      GITLAB__SHARED_SECRET: ${GITLAB__SHARED_SECRET}
      GITLAB__AUTH_TYPE: ${GITLAB__AUTH_TYPE:-oauth_token}
      OPENROUTER__KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      CONFIG__MODEL: ${CONFIG__MODEL}
      CONFIG__MODEL_REASONING: ${CONFIG__MODEL_REASONING}
      CONFIG__MODEL_WEAK: ${CONFIG__MODEL_WEAK}
      CONFIG__FALLBACK_MODELS: ${CONFIG__FALLBACK_MODELS}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:${PORT:-3000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pr-agent.rule=Host(`abc.def.com`)
      - traefik.http.routers.pr-agent.entrypoints=web
      - traefik.http.services.pr-agent.loadbalancer.server.port=${PORT:-3000}

networks:
  traefik:
    external: true
```

All the variables are passed down by gitlab's ci/cd variables.
